### ISSUE TITLE
Migration from `actix-web` to `Axum` 

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-backend#156]
@da2ce7 @WarmBeer and @josecelano agreed to migrate from actix-web to Axum. We also did it on the tracker:

- https://github.com/torrust/torrust-tracker/issues/160
- https://github.com/torrust/torrust-tracker/issues/143

The main reason in this case is we can have the same dependency in all torrust projects and there was no other reason not to do it. But after making the decision, a new issue was opened on the tracker:

https://github.com/torrust/torrust-tracker/issues/324

It seems Axum does not have a well-defined and tested implementation for client request timeouts. That could lead to denial of service attacks since once a client opens a connection, it's never closed automatically if the client is inactive for a long time.

I think we should postpone this issue for the time being @WarmBeer @da2ce7.

### Subtasks

- [x] https://github.com/torrust/torrust-index-backend/issues/187
- [x] https://github.com/torrust/torrust-index-backend/issues/174
- [x] https://github.com/torrust/torrust-index-backend/issues/198
- [x] https://github.com/torrust/torrust-index-backend/issues/178
- [x] https://github.com/torrust/torrust-index-backend/issues/183
- [x] https://github.com/torrust/torrust-index-backend/issues/179
- [x] https://github.com/torrust/torrust-index-backend/issues/181
- [x] https://github.com/torrust/torrust-index-backend/issues/188
- [x] https://github.com/torrust/torrust-index-backend/issues/182
- [x] https://github.com/torrust/torrust-index-backend/issues/180
- [x] https://github.com/torrust/torrust-index-backend/issues/197
- [x] https://github.com/torrust/torrust-index-backend/issues/208

### Related issues

- https://github.com/torrust/torrust-index-backend/issues/204
- https://github.com/torrust/torrust-index-backend/issues/39

**Comment by josecelano** [comment]
Hi @da2ce7, I have started with the migration.

**Comment by josecelano** [comment]
Done. There are two related issues to implement in the new Axum implementation.

- https://github.com/torrust/torrust-index-backend/issues/204
- https://github.com/torrust/torrust-index-backend/issues/39
